// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAbir5zrEvmOISysXyFcqnfuMJEi_MXiA',
    appId: '1:404818509524:web:27d273936d83d406864541',
    messagingSenderId: '404818509524',
    projectId: 'npci-hackathon-warriors',
    authDomain: 'npci-hackathon-warriors.firebaseapp.com',
    storageBucket: 'npci-hackathon-warriors.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjWGNnu-oo6CD102hXtvCDB3eRDGycTdU',
    appId: '1:404818509524:android:28294d6a9daeb7bc864541',
    messagingSenderId: '404818509524',
    projectId: 'npci-hackathon-warriors',
    storageBucket: 'npci-hackathon-warriors.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxQPL6HsRI0_B1YHLYbza9pQNExt1KajU',
    appId: '1:404818509524:ios:5c9f55b58f8055c1864541',
    messagingSenderId: '404818509524',
    projectId: 'npci-hackathon-warriors',
    storageBucket: 'npci-hackathon-warriors.firebasestorage.app',
    iosBundleId: 'com.example.npci',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxQPL6HsRI0_B1YHLYbza9pQNExt1KajU',
    appId: '1:404818509524:ios:5c9f55b58f8055c1864541',
    messagingSenderId: '404818509524',
    projectId: 'npci-hackathon-warriors',
    storageBucket: 'npci-hackathon-warriors.firebasestorage.app',
    iosBundleId: 'com.example.npci',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAbir5zrEvmOISysXyFcqnfuMJEi_MXiA',
    appId: '1:404818509524:web:b6a20132b3ee64a1864541',
    messagingSenderId: '404818509524',
    projectId: 'npci-hackathon-warriors',
    authDomain: 'npci-hackathon-warriors.firebaseapp.com',
    storageBucket: 'npci-hackathon-warriors.firebasestorage.app',
  );
}
